title: RA_0002_identification_extract_observables_from_email
stage: identification
automation:
  - thehive
author: '@atc_project'
creation_date: 31.01.2019
references: 
  - https://ubuntuincident.wordpress.com/2010/09/27/extract-email-attachments/
  - https://blog.thehive-project.org/2018/07/31/emlparser-a-new-cortex-analyzer-for-eml-files/
description: >
  Extract all observables from original phising email
workflow: |
  Extract the data for further response steps:

  - attachments (using munpack tool: `munpack email.eml`)
  - from, to, cc
  - subject of the email
  - received servers path
  - list of URLs from the text content of the mail body and attachments

  This Response Action could be automated with [TheHive EmlParser](https://blog.thehive-project.org/2018/07/31/emlparser-a-new-cortex-analyzer-for-eml-files/).
