confluence_space_name: "CLASSES"
confluence_space_home_page_name: 'classes Home'
confluence_name_of_root_directory: 'Atomic Threat Coverage'
md_name_of_root_directory: 'Atomic_Threat_Coverage'
list_of_detection_rules_directories: 
  - '../detectionrules'
list_of_triggering_directories: 
  - '../atomics'
confluence_rest_api_url: 'https://atomicthreatcoverage.atlassian.net/wiki/rest/api/'